#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLChess.PlayerAndEngines
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DWKDB")]
	public partial class DWKDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DWKDBDataContext() : 
				base(global::SQLChess.PlayerAndEngines.Properties.Settings.Default.DWKDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DWKDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DWKDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DWKDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DWKDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="chess.GetBestMove")]
		public ISingleResult<GetBestMoveResult> GetBestMove([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Moves", DbType="VarChar(MAX)")] string moves)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), moves);
			return ((ISingleResult<GetBestMoveResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="chess.SaveGame")]
		public int SaveGame([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Moves", DbType="VarChar(MAX)")] string moves, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GameID", DbType="Int")] System.Nullable<int> gameID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), moves, gameID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="chess.GetNewGame")]
		public ISingleResult<GetNewGameResult> GetNewGame([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SelfPlay", DbType="Bit")] System.Nullable<bool> selfPlay)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), selfPlay);
			return ((ISingleResult<GetNewGameResult>)(result.ReturnValue));
		}
	}
	
	public partial class GetBestMoveResult
	{
		
		private string _BestMove;
		
		public GetBestMoveResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BestMove", DbType="Char(64)")]
		public string BestMove
		{
			get
			{
				return this._BestMove;
			}
			set
			{
				if ((this._BestMove != value))
				{
					this._BestMove = value;
				}
			}
		}
	}
	
	public partial class GetNewGameResult
	{
		
		private System.Nullable<int> _GameID;
		
		private string _WebID;
		
		public GetNewGameResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GameID", DbType="Int")]
		public System.Nullable<int> GameID
		{
			get
			{
				return this._GameID;
			}
			set
			{
				if ((this._GameID != value))
				{
					this._GameID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WebID", DbType="Char(36)")]
		public string WebID
		{
			get
			{
				return this._WebID;
			}
			set
			{
				if ((this._WebID != value))
				{
					this._WebID = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
