#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStuff2
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DWKDB")]
	public partial class DWKDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
				
		public DWKDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DWKDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DWKDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DWKDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="chess.GetNewGame")]
		public ISingleResult<GetNewGameResult> GetNewGame([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SelfPlay", DbType="Bit")] System.Nullable<bool> selfPlay)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), selfPlay);
			return ((ISingleResult<GetNewGameResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="chess.GetBestMove")]
		public ISingleResult<GetBestMoveResult> GetBestMove([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Moves", DbType="VarChar(MAX)")] string moves)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), moves);
			return ((ISingleResult<GetBestMoveResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="chess.GetGameByGameID")]
		public ISingleResult<GetGameByGameIDResult> GetGameByGameID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GameID", DbType="Int")] System.Nullable<int> gameID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gameID);
			return ((ISingleResult<GetGameByGameIDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="chess.GetLastGame")]
		public ISingleResult<GetLastGameResult> GetLastGame()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetLastGameResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="chess.GetNewGame")]
		public ISingleResult<GetNewGameResult1> GetNewGame1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SelfPlay", DbType="Bit")] System.Nullable<bool> selfPlay)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), selfPlay);
			return ((ISingleResult<GetNewGameResult1>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="chess.GetSelfGameStats")]
		public ISingleResult<GetSelfGameStatsResult> GetSelfGameStats()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetSelfGameStatsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="chess.SaveGame")]
		public int SaveGame([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Moves", DbType="VarChar(MAX)")] string moves, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GameID", DbType="Int")] System.Nullable<int> gameID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), moves, gameID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="chess.GetGameByWebID")]
		public ISingleResult<GetGameByWebIDResult> GetGameByWebID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="WebID", DbType="Char(36)")] string webID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), webID);
			return ((ISingleResult<GetGameByWebIDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="chess.SaveMove")]
		public int SaveMove([global::System.Data.Linq.Mapping.ParameterAttribute(Name="WebID", DbType="Char(36)")] string webID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Board", DbType="Char(64)")] string board)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), webID, board);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="chess.SaveGameByWebID")]
		public int SaveGameByWebID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="WebID", DbType="Char(36)")] string webID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), webID);
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class GetNewGameResult
	{
		
		private System.Nullable<int> _GameID;
		
		private string _WebID;
		
		public GetNewGameResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GameID", DbType="Int")]
		public System.Nullable<int> GameID
		{
			get
			{
				return this._GameID;
			}
			set
			{
				if ((this._GameID != value))
				{
					this._GameID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WebID", DbType="Char(36)")]
		public string WebID
		{
			get
			{
				return this._WebID;
			}
			set
			{
				if ((this._WebID != value))
				{
					this._WebID = value;
				}
			}
		}
	}
	
	public partial class GetBestMoveResult
	{
		
		private string _BestMove;
		
		public GetBestMoveResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BestMove", DbType="Char(64)")]
		public string BestMove
		{
			get
			{
				return this._BestMove;
			}
			set
			{
				if ((this._BestMove != value))
				{
					this._BestMove = value;
				}
			}
		}
	}
	
	public partial class GetGameByGameIDResult
	{
		
		private int _MoveID;
		
		private string _Board;
		
		public GetGameByGameIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoveID", DbType="Int NOT NULL")]
		public int MoveID
		{
			get
			{
				return this._MoveID;
			}
			set
			{
				if ((this._MoveID != value))
				{
					this._MoveID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Board", DbType="Char(64) NOT NULL", CanBeNull=false)]
		public string Board
		{
			get
			{
				return this._Board;
			}
			set
			{
				if ((this._Board != value))
				{
					this._Board = value;
				}
			}
		}
	}
	
	public partial class GetLastGameResult
	{
		
		private int _MoveID;
		
		private string _Board;
		
		public GetLastGameResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoveID", DbType="Int NOT NULL")]
		public int MoveID
		{
			get
			{
				return this._MoveID;
			}
			set
			{
				if ((this._MoveID != value))
				{
					this._MoveID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Board", DbType="Char(64) NOT NULL", CanBeNull=false)]
		public string Board
		{
			get
			{
				return this._Board;
			}
			set
			{
				if ((this._Board != value))
				{
					this._Board = value;
				}
			}
		}
	}
	
	public partial class GetNewGameResult1
	{
		
		private System.Nullable<int> _GameID;
		
		private string _WebID;
		
		public GetNewGameResult1()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GameID", DbType="Int")]
		public System.Nullable<int> GameID
		{
			get
			{
				return this._GameID;
			}
			set
			{
				if ((this._GameID != value))
				{
					this._GameID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WebID", DbType="Char(36)")]
		public string WebID
		{
			get
			{
				return this._WebID;
			}
			set
			{
				if ((this._WebID != value))
				{
					this._WebID = value;
				}
			}
		}
	}
	
	public partial class GetSelfGameStatsResult
	{
		
		private System.Nullable<int> _MinimumDuration;
		
		private System.Nullable<int> _AverageDuration;
		
		private System.Nullable<int> _MaximumDuration;
		
		private System.Nullable<int> _MinimumMoveCount;
		
		private System.Nullable<int> _AverageMoveCount;
		
		private System.Nullable<int> _MaximumMoveCount;
		
		private System.Nullable<int> _CheckmateCount;
		
		private System.Nullable<int> _MaxGameID;
		
		public GetSelfGameStatsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinimumDuration", DbType="Int")]
		public System.Nullable<int> MinimumDuration
		{
			get
			{
				return this._MinimumDuration;
			}
			set
			{
				if ((this._MinimumDuration != value))
				{
					this._MinimumDuration = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AverageDuration", DbType="Int")]
		public System.Nullable<int> AverageDuration
		{
			get
			{
				return this._AverageDuration;
			}
			set
			{
				if ((this._AverageDuration != value))
				{
					this._AverageDuration = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaximumDuration", DbType="Int")]
		public System.Nullable<int> MaximumDuration
		{
			get
			{
				return this._MaximumDuration;
			}
			set
			{
				if ((this._MaximumDuration != value))
				{
					this._MaximumDuration = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinimumMoveCount", DbType="Int")]
		public System.Nullable<int> MinimumMoveCount
		{
			get
			{
				return this._MinimumMoveCount;
			}
			set
			{
				if ((this._MinimumMoveCount != value))
				{
					this._MinimumMoveCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AverageMoveCount", DbType="Int")]
		public System.Nullable<int> AverageMoveCount
		{
			get
			{
				return this._AverageMoveCount;
			}
			set
			{
				if ((this._AverageMoveCount != value))
				{
					this._AverageMoveCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaximumMoveCount", DbType="Int")]
		public System.Nullable<int> MaximumMoveCount
		{
			get
			{
				return this._MaximumMoveCount;
			}
			set
			{
				if ((this._MaximumMoveCount != value))
				{
					this._MaximumMoveCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckmateCount", DbType="Int")]
		public System.Nullable<int> CheckmateCount
		{
			get
			{
				return this._CheckmateCount;
			}
			set
			{
				if ((this._CheckmateCount != value))
				{
					this._CheckmateCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxGameID", DbType="Int")]
		public System.Nullable<int> MaxGameID
		{
			get
			{
				return this._MaxGameID;
			}
			set
			{
				if ((this._MaxGameID != value))
				{
					this._MaxGameID = value;
				}
			}
		}
	}
	
	public partial class GetGameByWebIDResult
	{
		
		private int _MoveID;
		
		private int _GameID;
		
		private string _Board;
		
		private System.Nullable<System.Guid> _WebID;
		
		private System.Nullable<long> _MoveNum;
		
		private System.Nullable<char> _Color;
		
		public GetGameByWebIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoveID", DbType="Int NOT NULL")]
		public int MoveID
		{
			get
			{
				return this._MoveID;
			}
			set
			{
				if ((this._MoveID != value))
				{
					this._MoveID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GameID", DbType="Int NOT NULL")]
		public int GameID
		{
			get
			{
				return this._GameID;
			}
			set
			{
				if ((this._GameID != value))
				{
					this._GameID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Board", DbType="Char(64) NOT NULL", CanBeNull=false)]
		public string Board
		{
			get
			{
				return this._Board;
			}
			set
			{
				if ((this._Board != value))
				{
					this._Board = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WebID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> WebID
		{
			get
			{
				return this._WebID;
			}
			set
			{
				if ((this._WebID != value))
				{
					this._WebID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoveNum", DbType="BigInt")]
		public System.Nullable<long> MoveNum
		{
			get
			{
				return this._MoveNum;
			}
			set
			{
				if ((this._MoveNum != value))
				{
					this._MoveNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Color", DbType="Char(1)")]
		public System.Nullable<char> Color
		{
			get
			{
				return this._Color;
			}
			set
			{
				if ((this._Color != value))
				{
					this._Color = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
